/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import br.com.model.VotacaoModel;
import br.com.ctrl.VotacaoController;

/**
 *
 * @author iarla
 */
public class VotacaoTela extends javax.swing.JFrame {
    VotacaoController controller;
    VotacaoController voto = new VotacaoController();
    /**
     * Creates new form VotacaoTela
     */
    public VotacaoTela(VotacaoController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Welcome = new javax.swing.JLabel();
        jLMatricula = new javax.swing.JLabel();
        jTInputMatricula = new javax.swing.JTextField();
        jTJornada = new javax.swing.JLabel();
        jRh40 = new javax.swing.JRadioButton();
        jRh44 = new javax.swing.JRadioButton();
        jLResultado40 = new javax.swing.JLabel();
        jLResultado44 = new javax.swing.JLabel();
        jLTotalPeople = new javax.swing.JLabel();
        jBRegistrar = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Welcome.setText("Bem-vindo à votação da jornada de trabalho!");

        jLMatricula.setText("Digite sua matrícula (ou digite 'sair' para encerrar a votação): ");

        jTInputMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTInputMatriculaActionPerformed(evt);
            }
        });

        jTJornada.setText("Escolha a jornada de trabalho:");

        buttonGroup1.add(jRh40);
        jRh40.setText("40 horas");

        buttonGroup1.add(jRh44);
        jRh44.setText("44 horas");

        jBRegistrar.setText("Registrar");
        jBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTInputMatricula, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jRh40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRh44)
                        .addGap(125, 125, 125))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLMatricula))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(Welcome))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jTJornada)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTotalPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLResultado40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLResultado44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jBRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTInputMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jTJornada)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRh40)
                    .addComponent(jRh44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLResultado40)
                .addGap(18, 18, 18)
                .addComponent(jLResultado44)
                .addGap(18, 18, 18)
                .addComponent(jLTotalPeople)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTInputMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTInputMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTInputMatriculaActionPerformed

    private void jBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarActionPerformed
        // TODO add your handling code here:
        String matricula = jTInputMatricula.getText();
        int escolha = (jRh40.isSelected()) ? 1 : (jRh44.isSelected() ? 2 : 0);
        
        if (!matricula.isEmpty()) {
            controller.registrarVoto(matricula, escolha);
            
            jLResultado40.setText("Total de votos para 40 horas: " + controller.getTotalVotos40Horas());
            jLResultado44.setText("Total de votos para 44 horas: " + controller.getTotalVotos44Horas());
            jLTotalPeople.setText("Total de funcionários que votaram: " + controller.getTotalVotos());
        } else {
            JOptionPane.showMessageDialog(this, "Matrícula não pode estar vazia. Por favor, insira uma matrícula válida.", "Erro", JOptionPane.ERROR_MESSAGE);
              }
    }//GEN-LAST:event_jBRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    VotacaoController controller = new VotacaoController(); // Crie uma instância de VotacaoController
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new VotacaoTela(controller).setVisible(true); // Passe o controller como argumento
        }
    });
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotacaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotacaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotacaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotacaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotacaoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Welcome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBRegistrar;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLResultado40;
    private javax.swing.JLabel jLResultado44;
    private javax.swing.JLabel jLTotalPeople;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRh40;
    private javax.swing.JRadioButton jRh44;
    private javax.swing.JTextField jTInputMatricula;
    private javax.swing.JLabel jTJornada;
    // End of variables declaration//GEN-END:variables
}
